/**
 * Polyhedra shape definitions for client-side Canvas rendering.
 * Shape data is generated by: node scripts/polyhedra/build-shapes.js
 */

import shapesData from './shapes.json'
import type { Shape } from './renderer'

// Cast through unknown because JSON arrays don't preserve tuple types
export const SHAPES = shapesData as unknown as Record<string, Shape>
export const SHAPE_NAMES = Object.keys(SHAPES)

export function getRandomShape(): string {
  return SHAPE_NAMES[Math.floor(Math.random() * SHAPE_NAMES.length)]
}

export function getShape(name: string): Shape {
  return SHAPES[name] || SHAPES.cube
}
